blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask a question on Discord! (or Reddit!) 
    url: https://discord.com/invite/pVVrrxd
    about: Check if your question has been answered in the documentation.
