name: "Build Linux tools"

on:
  workflow_dispatch:

env:
  FLALDF_FILE: "FlaLDF-v0.1-2-linux-x64.tar.gz"
  FLALDF_URL: "https://github.com/TokugawaHeavyIndustries/FlaLDF/releases/download/v0.1b/FlaLDF-v0.1-2-linux-x64.tar.gz"

  APPIMAGE_FILE: "linuxdeploy-x86_64.AppImage"
  APPIMAGE_URL: "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
  APPIMAGE_PLUGIN_FILE: "linuxdeploy-plugin-appimage-x86_64.AppImage"
  APPIMAGE_PLUGIN_URL: "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage"
  APPIMAGE_QT_FILE: "linuxdeploy-plugin-qt-x86_64.AppImage"
  APPIMAGE_QT_URL: "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"

jobs:
  build-tbc-tools:
    name: Build tbc-tools (x86_64)
    runs-on: ubuntu-latest
    container:
      image: oraclelinux:8
      options: --cap-add SYS_ADMIN --cap-add MKNOD --device /dev/fuse:mrw --security-opt apparmor:unconfined --privileged

    steps:
      - name: Set up DNF download cache
        id: dnf-cache
        uses: actions/cache@v3
        with:
          path: /var/cache/dnf
          key: dnfcache
          
      - name: Setup environment
        run: |
          dnf install --assumeyes --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
          dnf install --assumeyes --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm
          FORCE_DNF=1 /usr/bin/crb enable
          dnf --assumeyes install git file xz qt5-qtbase-devel qwt-qt5-devel fftw-devel ffmpeg-devel ffmpeg pkgconf-pkg-config make cmake sox python3-pip gcc-c++ python3-devel

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Create release directory
        run: mkdir release/

      - name: Build
        run: |
          cmake -B _build \
          -DCMAKE_BUILD_TYPE=Release \
          -DUSE_QT_VERSION=5 \
          -DBUILD_PYTHON=false

          cmake --build _build
          cmake --install _build --prefix AppDir/usr

      - name: Download linuxdeploy and build AppImage
        run: |
          curl -LJO ${{ env.APPIMAGE_URL }}
          curl -LJO ${{ env.APPIMAGE_PLUGIN_URL }}
          curl -LJO ${{ env.APPIMAGE_QT_URL }}

          chmod +x ${{ env.APPIMAGE_FILE }} ${{ env.APPIMAGE_PLUGIN_FILE }} ${{ env.APPIMAGE_QT_FILE }}

          EXTRA_QT_MODULES="core;gui;opengl;svg;widgets" ./${{ env.APPIMAGE_QT_FILE }} --appdir AppDir

          ./${{ env.APPIMAGE_FILE }} \
          --desktop-file resources/appimage/tools/tbc-tools.desktop \
          --icon-file assets/icons/vhs-decode.png \
          --appdir AppDir/ \
          --output appimage \
          --custom-apprun resources/appimage/tools/AppRun

          cp tbc-tools-x86_64.AppImage release/

      - name: Download FlaLDF
        run: |
          curl -LJO ${{ env.FLALDF_URL }}
          tar -xvf ${{ env.FLALDF_FILE }}
          cp flaldf release/

      - name: Copy scripts
        run: find scripts scripts/linux -maxdepth 1 -type f -executable -exec cp {} release/ \;

      - name: Create release archive
        run: tar -cvJSf tbc-tools.tar.xz --transform s/release/tbc-tools/ release/

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tbc-tools_linux_x86_64
          path: tbc-tools.tar.xz
          if-no-files-found: error
